### PR TITLE
various updates and improvements for v0.3.0

### PR DESCRIPTION
**Pull request by phip1611**
- merge of #16 
- prepare v0.3.0
- dependency updates
- code improvements
- example improvements

### CODE REVIEW

**Comment by phip1611** [comment]
Hm. @toothbrush7777777 I can't merge it like this, unfortunately.

If you run `cargo run --example show_chars_in_window --features all`, you will see:

image


The `�` character is pretty wide. How do we want to solve this? Jetbrains IDEs solve
it like this:

image


They just center it and cut it at the edges.

**Comment by toothbrush7777777** [comment]
@phip1611 Okay, I'll add some extra code to check if the character is too wide. Do you want to scale the character down or use only the centre part?

**Comment by phip1611** [comment]
I'm not sure what's the right thing to do, either.

If it's not too complicated, you can try to make the symbol smaller. Otherwise, we should center it and cut it at the edges

**Comment by phip1611** [comment]
@toothbrush7777777 Any update?

**Comment by toothbrush7777777** [comment]
The replacement character glyph does not exist in the Noto Sans Mono font. That glyph is coming from somewhere else.
I tried a couple of things with centring the glyph, which seems to work as far as I can tell, but I see an outlined box, not the glyph that you see, so I can't tell for certain.

**Comment by toothbrush7777777** [comment]
Anyway, I've fixed it in #18 by centring the glyphs.

**Comment by phip1611** [comment]
I still have this on my list! Sorry for the long delay

**Comment by phip1611** [comment]
This is a screenshot of the current rendering in https://github.com/rust-osdev/bootloader (on the right). The left side shows my system's default mono space rendering using Source Code Pro as font:

image


So either something that we do or Noto Sans Mono itself causes the high line height. Nevertheless, I think that this is the best that we can get - for what it is.

**Pull request merged**
